use std::collections::HashSet;
use std::sync::OnceLock;

use crate::db::Backend;
use crate::sql::lexer::TokenKind;

const COMMON_KEYWORDS: &str = "
ABORT ACTION ADD AFTER ALL ALTER ALWAYS ANALYZE AND ANY AS ASC ASYMMETRIC AT AUTHORIZATION BEFORE BEGIN
BETWEEN BOTH BY CALL CASCADE CASE CAST CHECK COLLATE COLUMN COLUMNS COMMENT COMMIT COMMITTED CONFLICT
CONSTRAINT CONSTRAINTS CREATE CROSS CURRENT CURRENT_CATALOG CURRENT_DATE CURRENT_ROLE CURRENT_SCHEMA CURRENT_TIME
CURRENT_TIMESTAMP CURRENT_USER CURSOR CYCLE DATA DATABASE DATABASES DEALLOCATE DECLARE DEFAULT DEFERRABLE DEFERRED
DEFINER DELETE DESC DESCRIBE DISTINCT DO DOMAIN DROP EACH ELSE ELSEIF END ESCAPE EXCEPT EXCLUDE EXCLUSIVE
EXECUTE EXISTS EXPLAIN EXTENSION FALSE FETCH FILTER FIRST FOLLOWING FOR FOREIGN FROM FULL FUNCTION FUNCTIONS
GENERATED GLOBAL GRANT GROUP GROUPS HANDLER HAVING IF IGNORE ILIKE IMMEDIATE IN INDEX INDEXES INHERIT INITIALLY
INNER INSERT INSTEAD INTERSECT INTO INVOKER IS ISNULL ISOLATION JOIN KEY LANGUAGE LAST LATERAL LEADING LEFT
LEVEL LIKE LIMIT LOCAL LOCK LOOP MATCH MATCHED MATERIALIZED MERGE MINUS NATURAL NEXT NO NOT NOTHING NOTNULL
NOWAIT NULL NULLS OF OFFSET ON ONLY OPTION OR ORDER OTHERS OUTER OVER OVERRIDING OWNER PARTITION PLACING
PRECEDING PRIMARY PRIVILEGES PROCEDURE PROCEDURES PUBLIC RANGE READ RECURSIVE REFERENCES REFRESH RELEASE RENAME
REPEATABLE REPLACE RESTRICT RETURN RETURNING RETURNS REVOKE RIGHT ROLE ROLLBACK ROLLUP ROW ROWS SAVEPOINT
SCHEMA SCHEMAS SECURITY SELECT SEQUENCE SEQUENCES SERIALIZABLE SESSION SESSION_USER SET SETS SHOW SIMILAR
SOME START STATEMENT STORED SYMMETRIC SYSTEM TABLE TABLES TABLESAMPLE TEMP TEMPORARY THEN TIES TO TRAILING
TRANSACTION TRIGGER TRUE TRUNCATE TYPE UNBOUNDED UNCOMMITTED UNION UNIQUE UNKNOWN UNLOGGED UNTIL UPDATE USAGE
USE USER USING VACUUM VALUE VALUES VARIADIC VERBOSE VIEW VIEWS VIRTUAL VOLATILE WHEN WHERE WHILE WINDOW WITH
WITHIN WITHOUT WORK WRITE ZONE CUBE GROUPING DISABLE ENABLE
";

const PG_KEYWORDS: &str = "
ACCESS ADMIN AGGREGATE ALSO ASSERTION ASSIGNMENT ATOMIC ATTACH ATTRIBUTE BACKWARD BREADTH CACHE CALLED CATALOG
CHAIN CHARACTERISTICS CHECKPOINT CLASS CLOSE CLUSTER COMMENTS CONCURRENTLY CONFIGURATION CONNECTION CONTENT
CONTINUE CONVERSION COPY COST CSV DEFAULTS DEFINER DELIMITER DELIMITERS DEPENDS DEPTH DETACH DICTIONARY
DISCARD DOCUMENT ENCODING ENCRYPTED ENUM EVENT EXPRESSION EXTERNAL FAMILY FINALIZE FORCE FORWARD FREEZE
GRANTED GREATEST HEADER HOLD IDENTITY IMMUTABLE IMPLICIT IMPORT INCLUDE INCLUDING INCREMENT INHERITS INLINE
INPUT INSENSITIVE LABEL LARGE LEAKPROOF LISTEN LOAD LOCATION LOCKED LOGGED MAPPING MAXVALUE METHOD MINVALUE
MODE MOVE NAMES NFC NFD NFKC NFKD NORMALIZE NORMALIZED NOTIFY OFF OIDS OPERATOR OPTIONS ORDINALITY OWNED
PARALLEL PARSER PARTIAL PASSING PASSWORD PLANS POLICY PREPARE PREPARED PRESERVE PRIOR PROCEDURAL PROGRAM
PUBLICATION QUOTE REASSIGN RECHECK REF REFERENCING REINDEX RELATIVE RESET RESTART ROUTINE ROUTINES RULE
SCROLL SEARCH SERVER SETOF SHARE SIMPLE SKIP SNAPSHOT SQL STABLE STANDALONE STATISTICS STDIN STDOUT
STORAGE STRICT STRIP SUBSCRIPTION SUPPORT SYSID TABLESPACE TEMPLATE TEXT TRANSFORM TRUSTED TYPES UNCOMMITTED
UNENCRYPTED UNLISTEN VALID VALIDATE VALIDATOR VERSION WHITESPACE WRAPPER XMLATTRIBUTES XMLTABLE YES
";

const MYSQL_KEYWORDS: &str = "
ACCESSIBLE ALGORITHM AUTO_INCREMENT AVG_ROW_LENGTH BINLOG BTREE CHANGE CHARACTER CHARSET CHECKSUM COLLATION
COLUMN_FORMAT COMPRESSED COMPRESSION CONCURRENT CONDITION CONTINUE DAY_HOUR DAY_MINUTE DAY_SECOND DEFINER
DELAYED DELAY_KEY_WRITE DETERMINISTIC DISCARD DISTINCTROW DIV DUAL DUMPFILE DUPLICATE DYNAMIC ENGINE ENGINES
ENCLOSED ERRORS ESCAPED EVENT EVENTS EXIT FIELDS FLUSH FORCE FULLTEXT GRANTS HASH HIGH_PRIORITY HOSTS
HOUR_MINUTE HOUR_SECOND IDENTIFIED INFILE INPLACE INSERT_METHOD INSTANT INVISIBLE ITERATE KEYS KEY_BLOCK_SIZE
KILL LEAVE LINES LOAD LOCKS LOGS LOW_PRIORITY MASTER MAX_ROWS MEMORY MIN_ROWS MOD MODIFY NO_WRITE_TO_BINLOG
OPTIMIZE OPTIONALLY OUTFILE PACK_KEYS PASSWORD PLUGINS PROCESSLIST PROFILE PROFILES PURGE QUERY QUICK
READS REDUNDANT REGEXP RELOAD REPAIR REPEAT REPLICA REQUIRE RESET RESIGNAL RLIKE ROW_FORMAT SECOND_MICROSECOND
SEPARATOR SHARED SHUTDOWN SIGNAL SLAVE SONAME SOUNDS SPATIAL SQL SQL_BIG_RESULT SQL_CALC_FOUND_ROWS
SQL_NO_CACHE SQL_SMALL_RESULT SSL STARTING STATUS STRAIGHT_JOIN SUPER TERMINATED UNDO UNLOCK UNSIGNED
USE_FRM UTC_DATE UTC_TIME UTC_TIMESTAMP VALIDATION VARIABLES WARNINGS XOR YEAR_MONTH ZEROFILL
";

const SQLITE_KEYWORDS: &str = "
ATTACH AUTOINCREMENT DETACH EXCLUSIVE FAIL GLOB INDEXED INSTEAD NOTHING PLAN PRAGMA QUERY RAISE REGEXP
REINDEX ROWID STRICT WITHOUT
";

const COMMON_TYPES: &str = "
BIGINT BINARY BIT BLOB BOOL BOOLEAN CHAR CHARACTER DATE DATETIME DEC DECIMAL DOUBLE FLOAT INT INTEGER
INTERVAL NCHAR NUMERIC NVARCHAR PRECISION REAL SMALLINT TIME TIMESTAMP VARBINARY VARCHAR VARYING TEXT
";

const PG_TYPES: &str = "
BIGSERIAL BIT BOX BYTEA CIDR CIRCLE DATERANGE FLOAT4 FLOAT8 INET INT2 INT4 INT4RANGE INT8 INT8RANGE JSON JSONB
LINE LSEG MACADDR MACADDR8 MONEY NAME NUMRANGE OID PATH PG_LSN POINT POLYGON REGCLASS REGPROC REGTYPE SERIAL
SERIAL2 SERIAL4 SERIAL8 SMALLSERIAL TIMESTAMPTZ TIMETZ TSQUERY TSRANGE TSTZRANGE TSVECTOR TXID_SNAPSHOT UUID
VARBIT XML CITEXT HSTORE RECORD VOID ANYELEMENT ANYARRAY
";

const MYSQL_TYPES: &str = "
ENUM GEOMETRY GEOMETRYCOLLECTION JSON LINESTRING LONGBLOB LONGTEXT MEDIUMBLOB MEDIUMINT MEDIUMTEXT
MULTILINESTRING MULTIPOINT MULTIPOLYGON POINT POLYGON SERIAL TINYBLOB TINYINT TINYTEXT YEAR
";

const SQLITE_TYPES: &str = "ANY";

const COMMON_FUNCTIONS: &str = "
ABS AVG CEIL CEILING COALESCE CONCAT COUNT EXP FLOOR GREATEST LEAST LENGTH LN LOG LOWER LTRIM MAX MIN MOD
NULLIF POWER RANK DENSE_RANK ROW_NUMBER LAG LEAD FIRST_VALUE LAST_VALUE NTH_VALUE NTILE PERCENT_RANK CUME_DIST
REPLACE ROUND RTRIM SIGN SQRT SUBSTR SUBSTRING SUM TRIM UPPER NOW RANDOM ABS
";

const PG_FUNCTIONS: &str = "
ARRAY_AGG ARRAY_APPEND ARRAY_CAT ARRAY_LENGTH ARRAY_POSITION ARRAY_REMOVE ARRAY_TO_STRING AGE BIT_LENGTH
BOOL_AND BOOL_OR BTRIM CARDINALITY CHAR_LENGTH CLOCK_TIMESTAMP CONCAT_WS CURRVAL DATE_PART DATE_TRUNC DECODE
ENCODE EVERY EXTRACT FORMAT GEN_RANDOM_UUID GENERATE_SERIES GENERATE_SUBSCRIPTS HAS_TABLE_PRIVILEGE INITCAP
JSON_AGG JSON_BUILD_ARRAY JSON_BUILD_OBJECT JSON_EACH JSON_EXTRACT_PATH JSON_OBJECT_AGG JSON_ARRAY_ELEMENTS
JSONB_AGG JSONB_BUILD_OBJECT JSONB_EACH JSONB_ARRAY_ELEMENTS JSONB_OBJECT_AGG JSONB_PRETTY JSONB_SET
JSONB_TYPEOF JSONB_PATH_QUERY JUSTIFY_DAYS LEFT LPAD MAKE_DATE MAKE_INTERVAL MAKE_TIMESTAMP MD5 NEXTVAL
OCTET_LENGTH OVERLAY PG_BACKEND_PID PG_CANCEL_BACKEND PG_SIZE_PRETTY PG_TABLE_SIZE PG_TERMINATE_BACKEND
PG_TOTAL_RELATION_SIZE PG_RELATION_SIZE PG_DATABASE_SIZE PG_SLEEP POSITION QUOTE_IDENT QUOTE_LITERAL
QUOTE_NULLABLE REGEXP_MATCH REGEXP_MATCHES REGEXP_REPLACE REGEXP_SPLIT_TO_ARRAY REGEXP_SPLIT_TO_TABLE REPEAT
REVERSE RIGHT RPAD SETVAL SPLIT_PART STARTS_WITH STATEMENT_TIMESTAMP STRING_AGG STRING_TO_ARRAY STRPOS
TO_CHAR TO_DATE TO_JSON TO_JSONB TO_NUMBER TO_TIMESTAMP TO_TSQUERY TO_TSVECTOR TRANSACTION_TIMESTAMP
TRANSLATE TRUNC UNNEST VERSION WIDTH_BUCKET PERCENTILE_CONT PERCENTILE_DISC MODE STDDEV VARIANCE
CURRENT_SETTING SET_CONFIG PG_TYPEOF ROW_TO_JSON
";

const MYSQL_FUNCTIONS: &str = "
ADDDATE ADDTIME AES_DECRYPT AES_ENCRYPT ANY_VALUE ASCII BENCHMARK BIN BIT_AND BIT_COUNT BIT_OR BIT_XOR CHAR_LENGTH
CHARSET CONCAT_WS CONNECTION_ID CONV CONVERT CONVERT_TZ CURDATE CURTIME DATABASE DATE_ADD DATE_FORMAT
DATE_SUB DATEDIFF DAY DAYNAME DAYOFMONTH DAYOFWEEK DAYOFYEAR ELT FIELD FIND_IN_SET FORMAT FOUND_ROWS
FROM_BASE64 FROM_DAYS FROM_UNIXTIME GET_LOCK GROUP_CONCAT HEX HOUR IF IFNULL INET_ATON INET_NTOA INSERT
INSTR IS_FREE_LOCK JSON_ARRAY JSON_ARRAYAGG JSON_CONTAINS JSON_EXTRACT JSON_KEYS JSON_LENGTH JSON_OBJECT
JSON_OBJECTAGG JSON_PRETTY JSON_SET JSON_TABLE JSON_TYPE JSON_UNQUOTE JSON_VALID LAST_DAY LAST_INSERT_ID LCASE
LEFT LOCATE LPAD MAKEDATE MD5 MICROSECOND MINUTE MONTH MONTHNAME OCT ORD PERIOD_ADD PI POSITION QUARTER
QUOTE RAND REGEXP_LIKE REGEXP_REPLACE REGEXP_SUBSTR RELEASE_LOCK REPEAT REVERSE RIGHT ROW_COUNT RPAD SECOND
SEC_TO_TIME SHA1 SHA2 SLEEP SPACE STR_TO_DATE STRCMP SUBDATE SUBSTRING_INDEX SYSDATE TIME_FORMAT
TIME_TO_SEC TIMEDIFF TIMESTAMPADD TIMESTAMPDIFF TO_BASE64 TO_DAYS TRUNCATE UCASE UNHEX UNIX_TIMESTAMP
UUID UUID_TO_BIN VERSION WEEK WEEKDAY WEEKOFYEAR YEARWEEK STD STDDEV VARIANCE
";

const SQLITE_FUNCTIONS: &str = "
CHANGES CHAR DATE DATETIME GLOB GROUP_CONCAT HEX IFNULL IIF INSTR JSON JSON_ARRAY JSON_ARRAY_LENGTH
JSON_EACH JSON_EXTRACT JSON_GROUP_ARRAY JSON_GROUP_OBJECT JSON_INSERT JSON_OBJECT JSON_PATCH JSON_REMOVE
JSON_REPLACE JSON_SET JSON_TREE JSON_TYPE JSON_VALID JULIANDAY LAST_INSERT_ROWID LIKELIHOOD LIKELY
LOAD_EXTENSION PRINTF QUOTE RANDOMBLOB SOUNDEX SQLITE_VERSION STRFTIME TIME TOTAL TOTAL_CHANGES TYPEOF
UNICODE UNLIKELY UNIXEPOCH ZEROBLOB FORMAT STRING_AGG
";

struct Sets {
    keywords: HashSet<String>,
    types: HashSet<String>,
    functions: HashSet<String>,
}

fn words(s: &str) -> impl Iterator<Item = String> + '_ {
    s.split_ascii_whitespace().map(str::to_string)
}

fn build(extra_kw: &str, extra_types: &str, extra_fn: &str) -> Sets {
    let types: HashSet<String> = words(COMMON_TYPES).chain(words(extra_types)).collect();
    let keywords = words(COMMON_KEYWORDS)
        .chain(words(extra_kw))
        .filter(|w| !types.contains(w))
        .collect();
    let functions = words(COMMON_FUNCTIONS).chain(words(extra_fn)).collect();
    Sets { keywords, types, functions }
}

fn sets(backend: Backend) -> &'static Sets {
    static PG: OnceLock<Sets> = OnceLock::new();
    static MY: OnceLock<Sets> = OnceLock::new();
    static LITE: OnceLock<Sets> = OnceLock::new();
    match backend {
        Backend::Postgres => PG.get_or_init(|| build(PG_KEYWORDS, PG_TYPES, PG_FUNCTIONS)),
        Backend::MySql => MY.get_or_init(|| build(MYSQL_KEYWORDS, MYSQL_TYPES, MYSQL_FUNCTIONS)),
        Backend::Sqlite => LITE.get_or_init(|| build(SQLITE_KEYWORDS, SQLITE_TYPES, SQLITE_FUNCTIONS)),
    }
}

/// Classifies a bare word. Keywords win over functions so `LEFT`, `REPLACE` highlight as keywords;
/// the highlighter re-labels a word followed by `(` as a function call.
pub fn classify(word: &str, backend: Backend) -> TokenKind {
    if word.len() > 40 || !word.is_ascii() {
        return TokenKind::Ident;
    }
    let mut buf = [0u8; 40];
    let up = &mut buf[..word.len()];
    up.copy_from_slice(word.as_bytes());
    up.make_ascii_uppercase();
    let up = std::str::from_utf8(up).unwrap_or("");
    let s = sets(backend);
    if s.keywords.contains(up) {
        TokenKind::Keyword
    } else if s.types.contains(up) {
        TokenKind::DataType
    } else if s.functions.contains(up) {
        TokenKind::Builtin
    } else {
        TokenKind::Ident
    }
}

fn sorted(set: &HashSet<String>) -> Vec<&'static str> {
    let mut v: Vec<&'static str> = set.iter().map(|s| -> &'static str { Box::leak(s.clone().into_boxed_str()) }).collect();
    v.sort_unstable();
    v
}

macro_rules! cached_list {
    ($name:ident, $field:ident) => {
        pub fn $name(backend: Backend) -> &'static [&'static str] {
            static PG: OnceLock<Vec<&'static str>> = OnceLock::new();
            static MY: OnceLock<Vec<&'static str>> = OnceLock::new();
            static LITE: OnceLock<Vec<&'static str>> = OnceLock::new();
            let cell = match backend {
                Backend::Postgres => &PG,
                Backend::MySql => &MY,
                Backend::Sqlite => &LITE,
            };
            cell.get_or_init(|| sorted(&sets(backend).$field))
        }
    };
}

cached_list!(keywords, keywords);
cached_list!(datatypes, types);
cached_list!(functions, functions);

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn classify_case_insensitive() {
        assert_eq!(classify("select", Backend::Postgres), TokenKind::Keyword);
        assert_eq!(classify("JsonB", Backend::Postgres), TokenKind::DataType);
        assert_eq!(classify("jsonb", Backend::MySql), TokenKind::Ident);
        assert_eq!(classify("group_concat", Backend::MySql), TokenKind::Builtin);
        assert_eq!(classify("users", Backend::Sqlite), TokenKind::Ident);
    }

    #[test]
    fn lists_are_sorted_and_nonempty() {
        let k = keywords(Backend::MySql);
        assert!(k.windows(2).all(|w| w[0] <= w[1]));
        assert!(k.contains(&"STRAIGHT_JOIN"));
        assert!(datatypes(Backend::Postgres).contains(&"TIMESTAMPTZ"));
    }
}
